<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Main Test Suites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>64814ed1-2393-4786-a3ba-690dc7ea47d9</testSuiteGuid>
   <testCaseLink>
      <guid>6ae08652-7549-4d31-9eeb-56e508e26c25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Profile</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4e6f8ec5-5a9f-4ad6-913c-b7a01adcdf64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Post Cek Tagihan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c86f2f7b-8e3a-44ae-8e1a-a39f1da172c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32099e76-ff9a-494f-b021-b3843c378531</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53684a59-78fc-4850-a634-a41eaad3fdd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f99b2bd7-9984-4103-858d-b6f0c768d7a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afed781b-14b0-4f19-b2db-60f944f714b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07f1345f-63f4-4fc5-9745-83f092aa06f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df4008f7-db57-4090-890a-417243bf72fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39bb217b-e433-453b-ab12-90dff2fceac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9ec8352-1f1c-4f91-a57f-fe78ab85e3ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f013d1e9-fb40-4f40-925b-a41f15277cc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Detail Product</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e8667b87-8b0a-47b0-94eb-84c3a278e9b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Post Transaksi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b58f21d8-5158-4915-ac33-a59ca1388a64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7325f5a6-539a-433f-b427-3f2ce067fecf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46fe1936-8e7a-47af-bb93-37eb5f955e72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac1ad6a2-75de-4182-ab85-378400ab7366</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>829e3338-200f-4009-8cca-1bc9bb5c16cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcf2fdb2-e43f-41c5-9ef6-3189ebea3cc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bed481aa-0af3-4126-b69b-2906b3ada06a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aabdd677-54e4-4940-bc9e-430b536ee3f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>329d5574-d3da-4ef5-aa83-0f751a2c7a4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebf422ea-f4f3-404a-872f-801774b4c241</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89b04655-1fe5-46ea-91a8-4468adcec4b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f239f2b-68a7-41bd-abc7-fe7faddfbcf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8346278-8410-492e-9729-f40691d40ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc2a47ec-a917-4f98-a125-f2e581a380f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>170bd83f-5a05-4058-b968-5d46bd2824c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2586ea19-a6f6-437e-bcfb-609bd73a36cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09900062-d3b6-4d42-a07a-254ec62ad686</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3519547e-80f4-48b4-b890-836ae564f9e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a4c3f90-930c-4edf-8924-5acabb2b7ed4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e454311-a1e2-4e49-8409-18c117db57bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13c1562c-d011-404c-a638-433736ceb636</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b32e86e7-07c9-4207-93b6-5969c19f2a9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9bfdb4e-1288-4b50-baee-3e2d40be78c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b119d94-5d9d-401b-8d18-b8b26b5a83c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>540ec864-d40d-407a-9a8d-0663a17fec23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ba08907-9c17-417f-b304-19b81199d3a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Harga Product</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>034e2c1d-5fab-4d9f-a6e2-faa315fcea72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Detil Transaksi</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fead04fd-5135-4d61-8a5a-9a6f35ffa273</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Nominal Product</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b38fba58-6ef6-4a6e-a149-9a4433c985d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Daftar Product</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0da5aaa4-04d4-47a5-bbd4-5ffe56a772fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Post Bayar Tagihan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3c3646fd-60ed-4d61-b275-d6fe7dcda34c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Riwayat Transaksi</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
